version: '3.8'
 
services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5001:5000"
    environment:
      MYSQL_HOST: myapp_mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    depends_on:
      - myapp_mysql
    networks:
      - mynet
 
  myapp_mysql:
    image: mysql:5.7
    container_name: myapp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - app_mysql_data:/var/lib/mysql
    networks:
      - mynet
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: myapp_mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - myapp_mysql
    networks:
      - mynet
 
networks:
  mynet:
    external: true
 
volumes:
  app_mysql_data:

